<Project>
  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <DebugType>portable</DebugType>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <WarningLevel>9999</WarningLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DefaultItemExcludesInProjectFolder>
      $(DefaultItemExcludesInProjectFolder);
      packages.lock.json;
      TestResults/**;
      *.lscache
    </DefaultItemExcludesInProjectFolder>
    <DefaultItemExcludes>
      $(DefaultItemExcludes);
      *.log;
      *.binlog
    </DefaultItemExcludes>
    <IsPackable>false</IsPackable>
    <NuGetAuditMode>all</NuGetAuditMode>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
